common/models/Article.php
<?php

namespace common\models;

use common\extensions\ActiveRecord;
use Helper\Scenario;
use Yii;
use yii\base\InvalidArgumentException;
use yii\behaviors\TimestampBehavior;
use yii\data\ArrayDataProvider;
use yii\helpers\ArrayHelper;
use yii\helpers\StringHelper;

/**
 * This is the model class for table "article".
 *
 * @property int $id
 * @property string $name
 * @property int $medium_id
 * @property string $url
 * @property string $abstract
 * @property int $is_premium
 * @property string $source_date
 * @property string $language
 * @property int $created_at
 * @property int $updated_at
 *
 * @property Medium $medium
 */
class Article extends ActiveRecord
{
    const SCENARIO_IMPORT = 'import';

    const FEED_PL = 'PL';
    const FEED_ENG = 'ENG';

    const FEEDS = [
        self::FEED_PL => 'user/1005024023/label/RPG-PL',
        self::FEED_ENG => 'user/1005024023/label/RPG-ENG'
    ];

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'article';
    }

    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            TimestampBehavior::class,
        ];
    }

    public function scenarios()
    {
        return ArrayHelper::merge([
            self::SCENARIO_IMPORT => []
        ], parent::scenarios());
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['is_premium', 'created_at', 'updated_at'], 'integer'],
            [['abstract'], 'string'],
            [['source_date'], 'safe'],
            [['language'], 'safe'],
            [['created_at', 'updated_at'], 'safe'],
            [['name', 'url'], 'string', 'max' => 255],
            [['medium_id'], 'exist', 'skipOnError' => true, 'targetClass' => Medium::class, 'targetAttribute' => ['medium_id' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'name' => Yii::t('app', 'Name'),
            'medium_id' => Yii::t('app', 'Medium ID'),
            'url' => Yii::t('app', 'Url'),
            'abstract' => Yii::t('app', 'Abstract'),
            'is_premium' => Yii::t('app', 'Is Premium'),
            'source_date' => Yii::t('app', 'Source Date'),
            'created_at' => Yii::t('app', 'Created At'),
            'updated_at' => Yii::t('app', 'Updated At'),
            'language' => Yii::t('app', 'Language'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getMedium()
    {
        return $this->hasOne(Medium::class, ['id' => 'medium_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPublisher()
    {
        return $this->hasOne(Publisher::class, ['id' => 'publisher_id'])->via('medium');
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getArticleTags()
    {
        return $this->hasMany(ArticleTag::class, ['article_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTags()
    {
        return $this->hasMany(Tag::class, ['id' => 'tag_id'])->via('articleTags');
    }

    public function load($data, $formName = null)
    {
        if (isset($data['Article']['tags'])) {
            $this->populateRelation('tags',
                Tag::find()->where(['id' => $data['Article']['tags']])->all()
            );
        }

        return parent::load($data, $formName);
    }

    public function save($runValidation = true, $attributeNames = null)
    {
        if ($this->scenario == self::SCENARIO_IMPORT) {
            $db = Yii::$app->getDb();

            $transaction = $db->beginTransaction();
            try {
                $mediumName = $this->medium->name;
                $medium = Medium::findByName($mediumName)->one();
                if (!$medium) {
                    $publisher = Publisher::findByName($mediumName)->one();
                    $medium = $this->medium;

                    if (!$publisher) {
                        $publisher = new Publisher(['name' => $mediumName]);
                        $publisher->save();
                        $medium->publisher_id = $publisher->id;
                    }

                    $medium->save();
                }
                $this->medium_id = $medium->id;

                $result = parent::save($runValidation, $attributeNames);
                $transaction->commit();
            } catch (\Exception $e) {
                $transaction->rollBack();
                $result = false;
            }
            return $result;
        }

        return parent::save($runValidation, $attributeNames);
    }

    /**
     * {@inheritdoc}
     */
    public function afterSave($insert, $changedAttributes) {
        $existingTags = $this->getArticleTags()->all();
        $formTags = $this->tags;

        if ($existingTags) {
            $tagsToDelete = \array_udiff($existingTags, $formTags, function ($objA, $objB) {
                $idA = \get_class($objA) == Tag::class ? $objA->id : $objA->tag_id;
                $idB = \get_class($objB) == Tag::class ? $objB->id : $objB->tag_id;

                return $idA - $idB;
            });

            foreach ($tagsToDelete as $tagToDelete) {
                /** @var ArticleTag $tagToDelete */
                $tagToDelete->delete();
            }
        }

        foreach ($this->tags as $tag) {
            if (!in_array($tag->id, ArrayHelper::getColumn($existingTags, 'tag_id'))) {
                $this->link('tags', $tag);
            }
        }

        parent::afterSave($insert, $changedAttributes);
    }

    /**
     * @param array $streamContents
     * @return ArrayDataProvider
     */
    public static function createDataProviderForStreamContents(array $streamContents)
    {
        $allModels = [];
        foreach ($streamContents['items'] as $streamContentsItem) {
            $model = new Article(static::createAttributesFromStreamContentsItem($streamContentsItem));
            $medium = new Medium(Medium::createAttributesFromStreamContentsItem($streamContentsItem));
            $model->populateRelation('medium', $medium);

            $allModels[] = $model;
        }

        return new ArrayDataProvider([
            'allModels' => $allModels,
            'pagination' => [
                'pageSize' => 80,
            ],
        ]);
    }

    /**
     * @param array $streamContentsItem
     * @return array
     */
    public static function createAttributesFromStreamContentsItem(array $streamContentsItem): array
    {
        $language = '';
        foreach ($streamContentsItem['categories'] as $category) {
            if (strpos($category, 'RPG-ENG')) {
                $language = 'ENG';
            }
            if (strpos($category, 'RPG-PL')) {
                $language = 'PL';
            }
        }

        $url = $streamContentsItem['canonical'][0]['href'] ?: '';

        return [
            'name' => StringHelper::truncateWords($streamContentsItem['title'], 15) ?: '',
            'language' => $language,
            'url' => $url,
            'source_date' => date('Y-m-d', $streamContentsItem['published'] ?: 0),
        ];
    }

    public function gridTags()
    {
        if (!$this->tags) {
            return [];
        }
        return ArrayHelper::map($this->tags, 'id', 'name');
    }

    static public function getLanguages()
    {
        return [
            Article::FEED_PL => Article::FEED_PL,
            Article::FEED_ENG => Article::FEED_ENG
        ];
    }
}

backend/controllers/MediumController.php
<?php

namespace backend\controllers;

use backend\external\Inoreader\Inoreader;
use common\models\Article;
use Yii;
use common\models\Medium;
use common\models\search\MediumSearch;
use yii\db\ActiveQuery;
use yii\db\IntegrityException;
use yii\filters\AccessControl;
use yii\helpers\ArrayHelper;
use yii\helpers\Json;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * MediumController implements the CRUD actions for Medium model.
 */
class MediumController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::class,
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Medium models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new MediumSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Medium model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Medium model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $request = Yii::$app->request;
        $model = new Medium();
        if ($model->load($request->post()) && $model->save()) {


            return $request->isAjax
                ? Json::encode(['id' => $model->id])
                : $this->redirect(['view', 'id' => $model->id]);
        }

        return $request->isAjax
            ? Json::encode(['id' => $model->id])
            : $this->render('create', ['model' => $model]);
    }

    /**
     * Updates an existing Medium model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {


            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Medium model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    public function actionSubscriptionsPl()
    {
        return $this->subscriptions(Article::FEED_PL);
    }

    public function actionSubscriptionsEng()
    {
        return $this->subscriptions(Article::FEED_ENG);
    }

    private function subscriptions($language)
    {
        /** @var Inoreader $inoreader */
        $inoreader = Yii::$app->inoreader->getInstance();

        if (is_string($inoreader)) {
            return $this->redirect($inoreader);
        }

        $response = $inoreader->reader()->subscriptionsList();
        $filteredSubscriptions = \array_filter($response['subscriptions'], function ($v) use ($language) {
            foreach ($v['categories'] as $category) {
                if ($category['label'] == 'RPG-'.$language) {
                    return true;
                }
            }
            return false;
        });

        $subscriptions = ArrayHelper::map($filteredSubscriptions, 'title', 'htmlUrl');
        ksort($subscriptions, SORT_FLAG_CASE | SORT_STRING);

        return $this->render('list', [
            'subscriptions' => $subscriptions,
        ]);
    }

    /**
     * Finds the Medium model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Medium the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Medium::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException(Yii::t('app', 'The requested page does not exist.'));
    }
}

backend/controllers/TagController.php
<?php

namespace backend\controllers;

use kartik\grid\EditableColumnAction;
use Yii;
use common\models\Tag;
use common\models\search\TagSearch;
use yii\filters\AccessControl;
use yii\helpers\ArrayHelper;
use yii\helpers\Json;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\Response;

/**
 * TagController implements the CRUD actions for Tag model.
 */
class TagController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::class,
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    public function actions()
    {
        return ArrayHelper::merge(parent::actions(), [
            'edit' => [
                'class' => EditableColumnAction::class,
                'modelClass' => Tag::class,
                'outputValue' => function ($model, $attribute) {
                    return $model->$attribute;
                },
                'showModelErrors' => true,
            ],
        ]);
    }

    /**
     * Lists all Tag models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new TagSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Tag model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Tag model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        if (Yii::$app->request->isAjax) {
            $postTags = Yii::$app->request->post('tags');
            $dbTags = ArrayHelper::map(
                Tag::find()->select(['id', 'name'])->where(['name' => $postTags])->asArray()->all(),
                'id', 'name'
            );
            $resultTags = [];
            foreach (array_diff($postTags, $dbTags) as $postTag) {
                if (!\is_numeric($postTag)) {
                    $model = new Tag();
                    $model->name = $postTag;
                    $model->save();
                    $resultTags[] = ['id' => $model->id, 'name' => $postTag];

                }
            }

            return Json::encode($resultTags);
        }
    }

    /**
     * Updates an existing Tag model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {


            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Tag model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    public function actionSearch($q = null, $id = null) {
        \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
        $out = ['results' => ['id' => '', 'text' => '']];
        if (!is_null($q)) {
            $data = Tag::find()->select('id, name AS text')
                ->where(['like', 'name', $q])
                ->limit(20)->asArray()->all();
            $out['results'] = $data;
        }
        elseif ($id > 0) {
            $out['results'] = ['id' => $id, 'text' => Tag::find($id)->name];
        }
        return $out;
    }

    /**
     * Finds the Tag model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Tag the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Tag::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException(Yii::t('app', 'The requested page does not exist.'));
    }
}

backend/views/article/_form.php
<?php

use common\models\Article;
use common\models\Medium;
use common\models\Tag;
use kartik\date\DatePicker;
use kartik\select2\Select2;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\Article */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="article-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>

	<?= $form->field($model, 'language')->dropDownList(Article::getLanguages()) ?>

    <?= $form->field($model, 'medium_id')->widget(Select2::class, [
        'data' => ArrayHelper::map(Medium::find()->select(['id', 'name'])->all(), 'id', 'name'),
        'options' => ['placeholder' => Yii::t('app', 'Select/add a medium ...')],
        'pluginOptions' => [
            'tags' => true,
            'tokenSeparators' => [','],
            'maximumInputLength' => 50,
        ],
        'pluginEvents' => [
            "select2:select" => "function() {
				var mediumName = $(this).val();
				var data = {
				  Medium: {name: mediumName}
				};
				$.post('".Url::to(['medium/create'])."', data, function (data) {
					var option = $('#article-medium_id option[value=\"'+mediumName+'\"]');
					if (data.id) {
						option.val(data.id);
					}
				}, 'json');
            }"]
    ]) ?>

    <?= $form->field($model, 'tags')->widget(Select2::class, [
        'data' => ArrayHelper::map(Tag::find()->select(['id', 'name'])->all(), 'id', 'name'),
        'options' => [
			'placeholder' => Yii::t('app', 'Select/add tags ...'),
            'multiple' => true
		],
        'pluginOptions' => [
            'tags' => true,
            'tokenSeparators' => [','],
            'maximumInputLength' => 100,
        ],
        'pluginEvents' => [
            "select2:select" => "function() {
				var data = {
				  tags: $(this).val()
				};
				$.post('".Url::to(['tag/create'])."', data, function (data) {
					$.each(data, function(key, element) {
						var option = $('#article-tags option[value=\"'+element.name+'\"]');
						option.val(element.id);	
					});
				}, 'json');
            }"]
    ]) ?>

    <?= $form->field($model, 'url')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'abstract')->textarea(['rows' => 6]) ?>

    <?= $form->field($model, 'is_premium')->checkbox() ?>

    <?= $form->field($model, 'source_date')->widget(DatePicker::class, [
        'type' => DatePicker::TYPE_INLINE,
        'pluginOptions' => [
            'format' => ' yyyy-mm-dd'
        ]
    ])
	?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Save'), ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/article/_search.php
<?php

use backend\helpers\AppHelper;
use common\models\Tag;
use kartik\select2\Select2;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\search\ArticleSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="article-search">
	<div class="row">
    <?php $form = ActiveForm::begin([
        'action' => [$page],
        'method' => 'get',
        'options' => [
            'data-pjax' => 1
        ],
    ]); ?>

	<div class="col-xs-10">
    <?= $form->field($model, 'tags')->widget(Select2::class, [
        'data' => ArrayHelper::map(AppHelper::getCachedModels(Tag::find()), 'id', 'name'),
        'options' => [
            'placeholder' => Yii::t('app', 'Select/add tags ...'),
            'multiple' => true
        ],
        'pluginOptions' => [
            'tags' => true,
            'allowClear' => true,
            'tokenSeparators' => [','],
            'maximumInputLength' => 100,
        ],
        'pluginEvents' => [
            "select2:select" => "function() {
				var data = {
				  tags: $(this).val()
				};
            }"]
    ]) ?>
	</div>

    <div class="form-group browse-submit col-xs-2">
        <?= Html::submitButton(Yii::t('app', 'Search'), ['class' => 'btn btn-primary']) ?>
    </div>
	</div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/article/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\Article */

$this->title = Yii::t('app', 'Create Article');
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Articles'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="article-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/article/index.php
<?php

use backend\helpers\AppHelper;
use common\helpers\BooleanHelper;
use common\models\Article;
use common\models\Medium;
use common\models\Tag;
use kartik\editable\Editable;
use kartik\grid\SerialColumn;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use kartik\grid\GridView;
use yii\helpers\Url;
use yii\widgets\Pjax;
/* @var $this yii\web\View */
/* @var $searchModel common\models\search\ArticleSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('app', 'Articles');
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="article-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a(Yii::t('app', 'Create Article'), ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?php Pjax::begin(); ?>
    <?php // echo $this->render('_search', ['model' => $searchModel, 'page' => 'index']); ?>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
			['class' => SerialColumn::class],
            ['attribute' => 'name',],
            [
				'attribute' => 'medium',
				'value' => 'medium.name',
				'filter' => ArrayHelper::map(AppHelper::getCachedModels(Medium::find()), 'id', 'name'),

			],
			[
				'class'=>'kartik\grid\EditableColumn',
				'attribute'=>'abstract',
                'editableOptions'=> [
					'formOptions' => ['action' => ['/article/edit']],
					'inputType' => Editable::INPUT_TEXTAREA
				]
			],
            [
				'attribute' => 'is_premium',
				'format' => 'boolean',
				'filter' => BooleanHelper::getListOptions(),
			],
            [
                'attribute' => 'source_date',
                'format' => 'date',
				'filterInputOptions' => [
					'autocomplete' => 'off',
					'class' => 'form-control'
				],
                'filterType' => GridView::FILTER_DATE_RANGE,
                'filterWidgetOptions' => ([
                    'attribute' => 'only_date',
                    'presetDropdown' => true,
                    'convertFormat' => false,
                    'pluginOptions' => [
                        'separator' => ' - ',
                        'format' => 'YYYY-MM-DD',
                        'locale' => [
                            'format' => 'YYYY-MM-DD'
                        ],
                    ],
                    'pluginEvents' => [
                        "apply.daterangepicker" => "function() { apply_filter('only_date') }",
                    ],
                ]),
            ],
            [
                'attribute' => 'language',
                'filter' => Article::getLanguages(),
            ],
            [
                'class' => 'backend\external\kartik\grid\EditableColumn',
                'attribute' => 'tags',
                'format' => 'html',
                'editableOptions' => [
                    'displayValue' => function ($model) {
    					$tags = implode(', ', $model->gridTags());
    					return $tags ?: '(not set)';
					},
                    'submitOnEnter' => false,
                    'header'=>'Tags',
                    'formOptions' => ['action' => ['/article/edit']],
                    'inputType'=>Editable::INPUT_SELECT2,
                    'options' => [
                        'attribute' => 'tags',
                        'data' => ArrayHelper::map(AppHelper::getCachedModels(Tag::find()), 'id', 'name'),
						'options' => [
                            'multiple' => true,
                        ],
                        'pluginOptions' => [
                            'allowClear' => true,
                            'tags' => true,
                            'tokenSeparators' => [','],
                            'maximumInputLength' => 100,
                        ],
                        'pluginEvents' => [
                            "select2:select" => "function() {
									var select = $(this);
									var data = {
									  tags: $(this).val()
									};
									$.post('".Url::to(['tag/create'])."', data, function (data) {
										$.each(data, function(key, element) {
											var option = select.find('option:last');
											option.val(element.id);
										});
									}, 'json');
								}"
                        ]
                    ],
                ],
            ],
            [
				'class' => 'yii\grid\ActionColumn',
				'template' => '{update} {delete} {link} {toggle-premium}',
				'buttons' => [

					'link' => function ($url, $model, $key) {
                        return Html::a(
							Html::tag('span', '', ['class' => 'glyphicon glyphicon-sunglasses']),
							$model->url, [
								'target' => '_blank',
								'title' => 'Open the article in a new tab',
								'aria-label' => 'Open the article in a new tab',
							]
						);
                    },
                    'toggle-premium' => function ($url, $model, $key) {
                        return Html::a(Html::tag('span', '',
							['class' => 'glyphicon glyphicon-asterisk']),
							$url, [
								'aria-label' => 'Toggle premium',
								'data-pjax' => 1,
								'data-method' => 'post',
							]
						);
                    },
					'delete' => function ($url, $model, $key) {
                        return Html::a(Html::tag('span', '',
							['class' => 'glyphicon glyphicon-trash']),
							$url, [
								'title' => 'Delete',
								'aria-label' => 'Delete',
								'data-confirm' => 'Are you sure you want to delete this item?',
								'data-pjax' => 1,
								'data-method' => 'post',
							]
						);
                    },
                    'update' => function ($url, $model, $key) {
                        return Html::a(Html::tag('span', '',
							['class' => 'glyphicon glyphicon-pencil']),
							$url, [
								'title' => 'Update',
								'aria-label' => 'Update',
								'data-pjax' => 0,
								'class' => 'update-article'
							]
						);
                    }
				]
			],
        ],
    ]); ?>

<?php Pjax::end();?>

</div>

backend/views/article/list.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;
/* @var $this yii\web\View */
/* @var $searchModel common\models\search\ArticleSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */
/* @var $groupedArticles array */

$this->title = Yii::t('app', 'Articles');
$this->params['breadcrumbs'][] = $this->title;

?><!-- wp:paragraph {"backgroundColor":"light-gray"} -->
<p class="has-background has-light-gray-background-color">Wstęp. Grafika pochodzi z  <a href="https://www.facebook.com/Welcome-to-sunny-B%C3%B6genhafen-The-Empire-in-pictures-673560376369502/">Welcome to sunny Bögenhafen: The Empire in pictures</a>.</p>
<!-- /wp:paragraph -->

<?php foreach ($feeds as $title => $feed): ?>
<!-- wp:paragraph {"align":"center","textColor":"white","backgroundColor":"black","fontSize":"medium"} -->
<p style="text-align:center" class="has-text-color has-background has-medium-font-size has-white-color has-black-background-color"><strong><?=$title?></strong></p>
<!-- /wp:paragraph -->

<?php foreach ($feed as $medium => $articles): ?><!-- wp:paragraph {"backgroundColor":"light-gray"} --><p class="has-background has-light-gray-background-color"><strong><?=$medium?></strong><?php $count = count($articles); foreach ($articles as $index => $article): ?><strong><a rel="noreferrer noopener" aria-label="<?=$article->name?> (otwiera się na nowej zakładce)" href="<?=$article->url?>" target="_blank"><br><?=$article->name?></a> [<?= implode(', ', $article->gridTags())?>]</strong><?php if ($article->abstract): ?><br><?=$article->abstract.($index+1 == $count ? '' : '<br>')?><?php endif; endforeach;?></p>
<!-- /wp:paragraph -->

<?php endforeach; ?>
<?php endforeach; ?>